/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AllanCoin } from "./AllanCoin";
export * as factories from "./factories";
export { AllanCoin__factory } from "./factories/AllanCoin__factory";
